name: "Chromatic"

# It would be nice to use the @chromeui/action to build storybook and deploy to chromatic
# Although I had problem with it to make turbosnap work
# You can check the issue here:
# https://github.com/IanVS/vite-plugin-turbosnap/issues/13

on:
  push:
    paths:
      - "packages/frontend/**"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 👈 Required to retrieve git history

      - name: Install dependencies
        run: yarn

      - name: Build Storybook
        run: yarn storybook:build

      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          buildScriptName: storybook:build
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          onlyChanged: true # 👈 Required option to enable TurboSnap
          storybookBuildDir: ./storybook-static
          exitOnceUploaded: true
          exitZeroOnChanges: true
          externals: |
            packages/frontend/tailwind.config.js
            *.css
            packages/frontend/src/static/fonts/**/*
          untraced: |
            packages/backend/package.json
            packages/shared/package.json
